### ISSUE TITLE
Access params passed at initialization are ignored in favour of  ~/.aws/credentials

### ISSUE THREAD

**Issue by awh-tokyo** [zshannon/cloudwatchlogger#20]
Initializing Cloudwatchlogger as follows:

```
l = CloudWatchLogger.new({access_key_id: '[redacted]', secret_access_key: '[redacted]'}, '/customer/main-site', 'stream-name', region: 'ap-northeast-1')
```

seems to ignore the credentials provided to the initializer and instead use the ones in ~/.aws/credentials.

**Comment by awh-tokyo** [comment]
It looks like Version 3 of the SDK expects the credentials to be passed differently from Version 2:

```
# using a credentials object
ec2 = Aws::EC2::Client.new(region: 'us-west-2', credentials: credentials)
```

Credentials object should be created by ```Aws::Credentials.new('akid', 'secret')```

**Comment by zshannon** [comment]
Feel free to put up a PR here
