### ISSUE TITLE
Better configuration

### ISSUE THREAD

**Issue by luizkowalski** [zshannon/cloudwatchlogger#8]
Right now, this is how we configure the library:
```ruby
log = CloudWatchLogger.new({access_key_id: 'YOUR_ACCESS_KEY_ID', secret_access_key: 'YOUR_SECRET_ACCESS_KEY'}, 'YOUR_CLOUDWATCH_LOG_GROUP')
```
This is far from ideal because:
1) we have a option params (the hash with access keys) **before** 
2) it is not clear what the params means without reading the code

The solution I see is introduce a configuration block, e.g.

```ruby
CloudwatchLogger.configure do |config|
  config.aws_key = xxx
  config.aws_secret = xxx
  config.log_group = xxxx
end
```

and have an instance of CloudwatchLogger saved into `CloudwatchLogger.current` (pretty much like Redis gem is doing) 

Ideas? Opinions?

**Comment by zshannon** [comment]
I dunno, this seems fine? The params in the configuration hash are names that show up elsewhere in AWS libraries, and match the terminology AWS uses, so I would prefer to keep `access_key_id` and `secret_access_key`.

Maybe there's a nearer middle-ground that moves the Cloudwatch Log Group name param the first param, and takes an optional hash of access keys as the second param (and we try to read these from the ENV as most AWS consumers do).

**Comment by luizkowalski** [comment]
the param in the `config` block was just an example. I would agree that we should keep `access_key_id` and `secret_access_key` as the name. 

> Maybe there's a nearer middle-ground that moves the Cloudwatch Log Group name param the first param

Definitely

>  and takes an optional hash of access keys as the second param

we can go further and copy AWS behavior: if no credentials are given, read from the environment variable `ACCESS_KEY_ID` and `SECRET_ACCESS_KEY`

**Comment by zshannon** [comment]
We might assume the presence of AWS keys in the environment, but I don't think we can assume that about an ENV var for the log group, and don't think we should require mutating the ENV (leaking info) to configure; so we'll need at least one config param for the log group.

With just one config param, I think a block is way overkill. Here's what I'd propose:

```ruby
module CloudWatchLogger
  module Client
    def self.new(log_group_name, credentials = nil, log_stream_name = nil, opts = {})
      unless log_group_name
        raise LogGroupNameRequired, 'log_group_name is required'
      end
      credentials ||= {
        access_key_id: ENV.get('ACCESS_KEY_ID'),
        secret_access_key: ENV.get('SECRET_ACCESS_KEY'),
      }
      CloudWatchLogger::Client::AWS_SDK.new(credentials, log_group_name, log_stream_name, opts)
    end

    ...

  end
end
```

**Comment by luizkowalski** [comment]
that was exactly what I meant! sorry for the confusion 😄
